// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OpenMahjong
{

public enum ActionType : uint
{
  ACTION_SYNC = 0,
  ACTION_SUTEHAI = 1,
  ACTION_CHII = 2,
  ACTION_PON = 3,
  ACTION_KAN = 4,
  ACTION_TSUMO = 5,
  ACTION_NAGASHI = 6,
};


}
