// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OpenMahjong
{

public enum MentsuType : byte
{
  TYPE_SHUNTSU = 0,
  TYPE_KOUTSU = 1,
  TYPE_MINKAN = 2,
  TYPE_ANKAN = 3,
  TYPE_ATAMA = 4,
};


}
