// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OpenMahjong
{

public enum MentsuFlag : byte
{
  FLAG_NONE = 0,
  FLAG_KAMICHA = 1,
  FLAG_TOIMEN = 2,
  FLAG_SIMOCHA = 3,
};


}
